/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Livre;

import Livre.Bibliotheque;
//import com.sun.jdi.connect.spi.Connection;
import java.sql.Connection;
import java.awt.event.ActionListener;

import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import javax.swing.JFormattedTextField;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.JPanel;
import javax.swing.Popup;
import net.proteanit.sql.DbUtils;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.*;
import javax.swing.JOptionPane.*;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.table.*;
import net.proteanit.sql.DbUtils;
import Livre.Livre;
import java.io.IOException;

import java.util.*;
import net.sourceforge.barbecue.Barcode;
import net.sourceforge.barbecue.Module;
import net.sourceforge.barbecue.output.Output;
import net.sourceforge.barbecue.output.OutputException;
/**
 *
 * @author Quentin
 */
public class jFrame extends  javax.swing.JFrame implements ActionListener {
        Bibliotheque mySQLConnect;
        
    Popup p; 
    
    private static final long serialVersionUID = 1L;
    private String titre;
private String auteur;
private String resume;
private String motsClefs;
        private int codeBarre;
private int Duree_vie;
        private Date date_achat;
        private double prix;
       private static final int WIDTH = 600;
   	private static final int HEIGHT = 90;
    /**
     * Creates new form JFrame
     */
        
        
         static Connection con;
	static PreparedStatement pst;
	 static ResultSet rs;
                    
    /**
     *
     */
    public void LivreDatabase(){
            
            getConnection();
        }
	
        public Connection getConnection(){
		try {
		Class.forName("com.mysql.cj.jdbc.Driver");
		String url = "jdbc:mysql://localhost:3306/projet_bibliotheque";
		con = (Connection) DriverManager.getConnection(url,"root","");
		
                
                }catch(ClassNotFoundException | SQLException e) {
			e.printStackTrace();
		}
		return con;
	}
        
    public jFrame() {
        
        
        initComponents();
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JFrame frame = this; 
        JMenuBar menuBar = new JMenuBar();
        frame.setJMenuBar(menuBar);
        frame.pack();
        frame.setVisible(true);
        
        //Création du menu fichier
        
        JMenu fileMenu = new JMenu("File");
        menuBar.add(fileMenu);
        
        //Option quitter le menu

        JMenu quitItem = new JMenu("Quit");
        menuBar.add(quitItem);
        
setSize(WIDTH, HEIGHT);
      
    	
        JPanel p1 = new JPanel(); 

        
        JButton bV = new JButton("Ajouter Livre");
     
        JButton bA = new JButton("Enregistrer Livre");
     
        bV.addActionListener(this);
        bA.addActionListener(this);

   
        
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        bV = new javax.swing.JButton();
        bA = new javax.swing.JButton();
        txtauthor = new javax.swing.JTextField();
        txttitle = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtresume = new javax.swing.JTextField();
        txtmotsclefs = new javax.swing.JTextField();
        txtdatetachat = new javax.swing.JTextField();
        txtdureevie = new javax.swing.JTextField();
        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        lbl7 = new javax.swing.JLabel();
        lbl8 = new javax.swing.JLabel();
        BarCode = new javax.swing.JButton();
        jMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        quitItem = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ajout Livre");

        jLabel2.setText("Enregistre un livre :");

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tab);

        bV.setText("Ajout Livre");
        bV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVActionPerformed(evt);
            }
        });

        bA.setText("Enregistrer Livre");
        bA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAActionPerformed(evt);
            }
        });

        txtauthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtauthorActionPerformed(evt);
            }
        });

        txtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpriceActionPerformed(evt);
            }
        });

        lbl1.setText("code-barre");

        lbl2.setText("prix");

        lbl3.setText("resume");

        lbl4.setText("mots-clefs");

        lbl5.setText("date achat");

        lbl6.setText("duree-vie");

        lbl7.setText("titre");

        lbl8.setText("auteur");

        BarCode.setText("BarCode");
        BarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BarCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(24, 24, 24)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(lbl8)
                                                    .addComponent(lbl7)
                                                    .addComponent(lbl2)
                                                    .addComponent(lbl3)))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(lbl4))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(lbl6)
                                                .addComponent(lbl5)))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtdatetachat, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                                            .addComponent(txtdureevie)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lbl1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BarCode))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(bV))
                                    .addComponent(txtmotsclefs, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtresume, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txttitle, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(188, 188, 188)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bA))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BarCode)
                            .addComponent(lbl1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtauthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtresume, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmotsclefs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdatetachat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdureevie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl6))
                        .addGap(27, 27, 27)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bV)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(bA))
                .addContainerGap())
        );

        fileMenu.setText("File");
        jMenuBar.add(fileMenu);

        quitItem.setText("Quit");
        jMenuBar.add(quitItem);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVActionPerformed

           if(evt.getSource()== bV) {
                  
        String auteur = txtauthor.getText();
     String  titre = txttitle.getText();
    String prix = txtprice.getText();
    String resume = txtresume.getText();
    String motsclefs = txtmotsclefs.getText();
    String date_achat = txtdatetachat.getText();
    String duree_vie = txtdureevie.getText();
    
    this.mySQLConnect = new Bibliotheque();
                
       
        
   String sql = "INSERT INTO ouvrage (CodeBarre, Auteur, Titre, Prix, Resume, MotsClefs, DateDAchat,DureeDeVie) values ('"
                    +"','"+ auteur+"','"+titre+"','"+prix+"','"+resume+"','"+motsclefs+"','"+date_achat+"','"+duree_vie+"')";
        
        
        try{
                PreparedStatement stmt = mySQLConnect.connect().prepareStatement(sql);
                stmt.executeUpdate();
        } catch(SQLException a){
              a.printStackTrace();
                         showMessageDialog(this, "Livre ajouter", "Validation", INFORMATION_MESSAGE);
            
            
        } finally{
            mySQLConnect.disconnect();
        
          //showMessageDialog(this,"Erreur dans la saisie des informations","Erreur de saisie", WARNING_MESSAGE);

        
        }
        
    } else if (evt.getSource() == bV){
        
        txtauthor.setText(null);
         txttitle.setText(null);
    }
           
                  //button.JOptionPane.showMessageDialog(this, "Can't Open.");

        // TODO add your handling code here:
    }//GEN-LAST:event_bVActionPerformed

    private void bAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAActionPerformed
   
        //public void savelivre(){
    if(evt.getSource()== bA) {
            
      
        String auteur = txtauthor.getText();
     String  titre = txttitle.getText();
    String prix = txtprice.getText();
    String resume = txtresume.getText();
    String motsclefs = txtmotsclefs.getText();
    String date_achat = txtdatetachat.getText();
    String duree_vie = txtdureevie.getText();
  
      this.mySQLConnect = new Bibliotheque();

      String sql = "UPDATE ouvrages SET Titre='Burguess WHERE id in (1,3)"
	      

 try{
            PreparedStatement stmt = mySQLConnect.connect().prepareStatement(sql);
            int rs = stmt.executeUpdate(sql);
           // tab.setModel(DbUtils.resultSetToTableModel(rs));
 } catch(SQLException a){
     
     a.printStackTrace();
 } finally{
     mySQLConnect.disconnect();
    
     
 showMessageDialog(this, "Livre Enregistrer.", "Validation", INFORMATION_MESSAGE);
         
        
        }
        
    } else if (evt.getSource() == bA){
        
        txtauthor.setText(null);
         txttitle.setText(null);
    }
    


// TODO add your handling code here:
    }//GEN-LAST:event_bAActionPerformed

    private void txtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpriceActionPerformed
    
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtpriceActionPerformed

    private void txtauthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtauthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtauthorActionPerformed

    private void BarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BarCodeActionPerformed
        // TODO code application logic here
    
            String[] args = null;
            try {
                Barcode2.main(args);
                /**
                 *
                 */
                
                // JFrame f = new JFrame(); //creates jframe f
            } catch (Exception ex) {
                Logger.getLogger(jFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_BarCodeActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
  

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BarCode;
    private javax.swing.JButton bA;
    private javax.swing.JButton bV;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    private javax.swing.JLabel lbl7;
    private javax.swing.JLabel lbl8;
    private javax.swing.JMenu quitItem;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txtauthor;
    private javax.swing.JTextField txtdatetachat;
    private javax.swing.JTextField txtdureevie;
    private javax.swing.JTextField txtmotsclefs;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtresume;
    private javax.swing.JTextField txttitle;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {          
   
      
 
    
  }

   
    }

   

   

   
    

  






          
        
    


    
   

